/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aiassignment2;

import java.awt.List;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import javax.swing.JFileChooser;

/**
 *
 * @author Dihan
 */
public class StockForm extends javax.swing.JFrame {

    /**
     * Creates new form StockForm
     */
    private String choseFile = new String();
    private LinkedList<StockInfo> stockList = new LinkedList<StockInfo>();
    private int closingPriceRange;
    private LinkedList<RenkoBlock> renkoChart = new LinkedList<RenkoBlock>();

    public StockForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtFile = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnHillClimbRun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnHillClimbRun.setText("Hill Climb");
        btnHillClimbRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHillClimbRunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnBrowse)
                        .addGap(18, 18, 18)
                        .addComponent(edtFile, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHillClimbRun)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addGap(31, 31, 31)
                .addComponent(btnHillClimbRun)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:

        final JFileChooser fileChooser = new JFileChooser();

        fileChooser.showOpenDialog(this);

        edtFile.setText(fileChooser.getName(fileChooser.getSelectedFile()));
        choseFile = edtFile.getText();

        try {

            FileReader fr = new FileReader(choseFile);
            BufferedReader br = new BufferedReader(fr);
            String line;
            int firstLoop = 0;
            Integer maxClosingPrice = null, minClosingPrice = null;
            while ((line = br.readLine()) != null) {
                String date;
                int highPrice;
                int lowPrice;
                int closingPrice;

                String[] split = line.split("\\s+");

                if (split.length == 5) {
                    StockInfo stock = new StockInfo(split[0], Integer.parseInt(split[1]), Integer.parseInt(split[2]), Integer.parseInt(split[3]));
                    stockList.add(stock);

                    if (firstLoop == 0) {
                        maxClosingPrice = Integer.parseInt(split[1]);
                        minClosingPrice = Integer.parseInt(split[1]);
                        firstLoop++;
                    }

                    if (Integer.parseInt(split[1]) >= maxClosingPrice) {
                        maxClosingPrice = Integer.parseInt(split[1]);
                    } else if (Integer.parseInt(split[1]) <= minClosingPrice) {
                        minClosingPrice = Integer.parseInt(split[1]);
                    }
                }
            }

            closingPriceRange = (int) ((maxClosingPrice - minClosingPrice) * 0.01);
            closingPriceRange = Math.round(closingPriceRange);

        } catch (IOException e) {
            System.err.println(e.toString());
        }

        //Build renko chart info
        int count = 0;
        int previousClosingPrice = stockList.get(count)._closingPrice;
        for (StockInfo stock : stockList) {

            int test = stock._closingPrice - previousClosingPrice;

            if (test < 0) {
                if (test <= -closingPriceRange) {
                    RenkoBlock block = new RenkoBlock();
                    block.setColor("white");
                    block.setStockInfo(stock);
                    block.setDate(stock._date);
                    block.setPrice(stock._closingPrice);
                    renkoChart.add(block);
                    previousClosingPrice = previousClosingPrice - closingPriceRange;
                }

            }
            if (test > 0) {
                if (test >= closingPriceRange) {
                    RenkoBlock block = new RenkoBlock();
                    block.setColor("black");
                    block.setStockInfo(stock);
                    block.setDate(stock._date);
                    block.setPrice(stock._closingPrice);
                    renkoChart.add(block);

                    previousClosingPrice = previousClosingPrice + closingPriceRange;
                }

            } else {
                //System.out.println("No renko block added");
            }

        }

        System.out.println("Renko Chart size " + renkoChart.size());


    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnHillClimbRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHillClimbRunActionPerformed
        // TODO add your handling code here:
        hillClimber hillClimber = new hillClimber(renkoChart);
        hillClimber.run();
    }//GEN-LAST:event_btnHillClimbRunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnHillClimbRun;
    private javax.swing.JTextField edtFile;
    // End of variables declaration//GEN-END:variables
}
